services:
  - type: web
    name: websocket-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Server.py
    envVars:
      - key: PORT
        value: 8000 